# Generated by Django 4.1.2 on 2022-10-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_editorinchief_editor_author'),
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='user',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to='accounts.author'),
        ),
    ]
