# Generated by Django 4.1.2 on 2022-10-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_rename_description_manuscript_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='abstract',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('minor', 'Minor'), ('major', 'Major'), ('under process', 'under process')], default='under process', max_length=50),
        ),
    ]
