# Generated by Django 4.1.2 on 2022-10-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_alter_manuscript_abstract_alter_manuscript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
