# Generated by Django 4.1.2 on 2022-10-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_journal_doi_alter_journal_issn_online_and_more'),
        ('manuscripts', '0005_manuscript_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to='journals.journal'),
        ),
    ]
