# Generated by Django 4.1.2 on 2022-10-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0007_remove_manuscript_file_manuscript_abstract_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Figures',
            new_name='Figure',
        ),
    ]
