# Generated by Django 4.1.2 on 2022-11-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_keyword_reviewer_keywords'),
        ('manuscripts', '0008_rename_figures_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuRev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.manuscript')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.reviewer')),
            ],
        ),
    ]
