# Generated by Django 4.1.2 on 2022-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_editorinchief_editor_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
        migrations.AddField(
            model_name='author',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
        migrations.AddField(
            model_name='editor',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
        migrations.AddField(
            model_name='editorinchief',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
    ]
