# Generated by Django 4.1.2 on 2022-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_reviewer_editor_eicstaff_editorstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('eic', 'Editor in Chief'), ('eic_staff', 'Eic Staff'), ('e_staff', 'E Staff')], default='author', max_length=50),
        ),
    ]
