# Generated by Django 4.1.2 on 2022-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_image',
            field=models.ImageField(blank=True, default='/media/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='user_image',
            field=models.ImageField(blank=True, default='/media/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='editorinchief',
            name='user_image',
            field=models.ImageField(blank=True, default='/media/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='editorstaff',
            name='user_image',
            field=models.ImageField(blank=True, default='/media/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='eicstaff',
            name='user_image',
            field=models.ImageField(blank=True, default='/media/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='user_image',
            field=models.ImageField(blank=True, default='/media/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
    ]
