# Generated by Django 4.1.2 on 2022-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_author_user_image_alter_editor_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='keyword',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
