# Generated by Django 4.1.2 on 2022-11-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_reviewer_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
