# Generated by Django 4.1.2 on 2022-11-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_journal_doi_alter_journal_issn_online_and_more'),
        ('accounts', '0012_rename_keyword_reviewer_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_image',
            field=models.ImageField(blank=True, default='/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='user_image',
            field=models.ImageField(blank=True, default='/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='editorinchief',
            name='user_image',
            field=models.ImageField(blank=True, default='/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='editorstaff',
            name='user_image',
            field=models.ImageField(blank=True, default='/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='eicstaff',
            name='user_image',
            field=models.ImageField(blank=True, default='/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='user_image',
            field=models.ImageField(blank=True, default='/user_image/placeholder.jpeg', null=True, upload_to='user_image/'),
        ),
    ]
