# Generated by Django 4.1.2 on 2022-10-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
    ]
