# Generated by Django 4.1.2 on 2022-10-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_remove_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_image/'),
        ),
    ]
