# Generated by Django 4.1.2 on 2022-10-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journal_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='doi',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='journal',
            name='issn_online',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='journal',
            name='issn_print',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
