# Generated by Django 4.1.2 on 2022-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journal_doi_journal_issn_online_journal_issn_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='doi',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_online',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_print',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
